version: '3'

services:
  database:
    image: mariadb:${MARIADB_VERSION:11.3.2}
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:travel_booking}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:root}
      MYSQL_USER: ${MYSQL_USER:}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:}
    volumes:
      - database_data:/var/lib/mysql

volumes:
  database_data:
