controllers:
    resource: ../src/Controller/
    type: attribute

login:
    path: /login
    controller: App\Controller\AuthenticationController::login

logout:
    path: /logout
    controller: App\Controller\AuthenticationController::logout

register:
    path: /register
    controller: App\Controller\AuthenticationController::register

view_travel:
    path: /travel/{id}
    controller: App\Controller\BookingController::viewTravel
    methods: [GET, POST]
    requirements:
        id: '\d+'

my_travels:
    path: /my_travels
    controller: App\Controller\BookingController::myTravels

# Define other routes for your application as needed