controllers:
    resource: ../src/Controller/
    type: attribute

login:
    path: /login
    controller: App\Controller\SecurityController::login

logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

# Define other routes for your application as needed