controllers:
    resource: ../src/Controller/
    type: attribute

login:
    path: /login
    controller: App\Controller\AuthenticationController::login

logout:
    path: /logout
    controller: App\Controller\AuthenticationController::logout

register:
    path: /register
    controller: App\Controller\AuthenticationController::register

# Define other routes for your application as needed